### ISSUE TITLE
LDAP requirement

### ISSUE THREAD

**Issue by oobeLachlan** [3rd-party-integrations/github-team-sync#146]
Please add guidance for GHES running in Azure to use this without requiring LDAP via AADDS. 

https://learn.microsoft.com/en-us/azure/active-directory/fundamentals/auth-ldap

Can't use AAD User Provisioning either because of Github SCIM API requirement. 

https://learn.microsoft.com/en-us/azure/active-directory/saas-apps/github-provisioning-tutorial

**Comment by primetheus** [comment]
>Please add guidance for GHES running in Azure to use this without requiring LDAP via AADDS.
>https://learn.microsoft.com/en-us/azure/active-directory/fundamentals/auth-ldap

@oobeLachlan thank you for opening this issue! There is currently an example environment file for running AzureAD without LDAP ([.env.example.aad](https://github.com/github/github-team-sync/blob/main/.env.example.aad)), and it makes use of [msal](https://github.com/github/github-team-sync/blob/main/Pipfile#L25) to authenticate. If you use this configuration it will be SAML rather than LDAP.

>Can't use AAD User Provisioning either because of Github SCIM API requirement.
>https://learn.microsoft.com/en-us/azure/active-directory/saas-apps/github-provisioning-tutorial

This tool will only handle user creation if your GHES instance is configured with `Local` authentication. Otherwise you will need to leverage the GitHub native feature for user provisioning. The main purpose of this utility is to synchronize `GitHub Team` membership with users in groups within your directory. In other words, the users should already exist in GitHub and be provisioned through some other means.

**Comment by primetheus** [comment]
@oobeLachlan if you still need help with this, please feel free to reach back out
